
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftIGUAL_IGUALDIFERENTEMAYOR_QUEMENOR_QUEMAYOR_IGUALMENOR_IGUALleftMASMENOSleftPORDIVMODrightNOTAMPERSAND AND CADENA CARACTER COMA COR_DER COR_IZQ DECIMAL DIFERENTE DIV DIV_IGUAL DOS_PUNTOS ENTERO FLECHA FLECHA_DOBLE ID IGUAL IGUAL_IGUAL LLAVE_DER LLAVE_IZQ MAS MAS_IGUAL MAYOR_IGUAL MAYOR_QUE MENOR_IGUAL MENOR_QUE MENOS MENOS_IGUAL MOD MOD_IGUAL NOT OR PAR_DER PAR_IZQ POR POR_IGUAL PUNTO PUNTO_COMA R_BOOL R_BREAK R_CHAR R_CONTINUE R_ELSE R_F64 R_FALSE R_FN R_I32 R_IF R_LET R_LOOP R_MATCH R_MUT R_PRINTLN R_RETURN R_STRING R_STRUCT R_TRUE R_WHILEprograma : instruccionesinstrucciones : instrucciones instruccion\n| instruccioninstruccion : R_LET R_MUT ID DOS_PUNTOS tipo IGUAL expresion PUNTO_COMA\n| R_LET ID DOS_PUNTOS tipo IGUAL expresion PUNTO_COMAtipo : R_I32 \n| R_F64 \n| R_STRING \n| R_BOOLexpresion : expresion MAS expresion\n| expresion MENOS expresion\n| expresion POR expresion\n| expresion DIV expresion\n| expresion MOD expresionexpresion : ENTERO\n| DECIMAL\n| CADENA\n| R_TRUE\n| R_FALSE'
    
_lr_action_items = {'R_LET':([0,2,3,5,26,32,],[4,4,-3,-2,-5,-4,]),'$end':([1,2,3,5,26,32,],[0,-1,-3,-2,-5,-4,]),'R_MUT':([4,],[6,]),'ID':([4,6,],[7,8,]),'DOS_PUNTOS':([7,8,],[9,10,]),'R_I32':([9,10,],[12,12,]),'R_F64':([9,10,],[13,13,]),'R_STRING':([9,10,],[14,14,]),'R_BOOL':([9,10,],[15,15,]),'IGUAL':([11,12,13,14,15,16,],[17,-6,-7,-8,-9,18,]),'ENTERO':([17,18,27,28,29,30,31,],[20,20,20,20,20,20,20,]),'DECIMAL':([17,18,27,28,29,30,31,],[21,21,21,21,21,21,21,]),'CADENA':([17,18,27,28,29,30,31,],[22,22,22,22,22,22,22,]),'R_TRUE':([17,18,27,28,29,30,31,],[23,23,23,23,23,23,23,]),'R_FALSE':([17,18,27,28,29,30,31,],[24,24,24,24,24,24,24,]),'PUNTO_COMA':([19,20,21,22,23,24,25,33,34,35,36,37,],[26,-15,-16,-17,-18,-19,32,-10,-11,-12,-13,-14,]),'MAS':([19,20,21,22,23,24,25,33,34,35,36,37,],[27,-15,-16,-17,-18,-19,27,-10,-11,-12,-13,-14,]),'MENOS':([19,20,21,22,23,24,25,33,34,35,36,37,],[28,-15,-16,-17,-18,-19,28,-10,-11,-12,-13,-14,]),'POR':([19,20,21,22,23,24,25,33,34,35,36,37,],[29,-15,-16,-17,-18,-19,29,29,29,-12,-13,-14,]),'DIV':([19,20,21,22,23,24,25,33,34,35,36,37,],[30,-15,-16,-17,-18,-19,30,30,30,-12,-13,-14,]),'MOD':([19,20,21,22,23,24,25,33,34,35,36,37,],[31,-15,-16,-17,-18,-19,31,31,31,-12,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,5,]),'tipo':([9,10,],[11,16,]),'expresion':([17,18,27,28,29,30,31,],[19,25,33,34,35,36,37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> instrucciones','programa',1,'p_programa','parser.py',20),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_lista','parser.py',24),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_lista','parser.py',25),
  ('instruccion -> R_LET R_MUT ID DOS_PUNTOS tipo IGUAL expresion PUNTO_COMA','instruccion',8,'p_instruccion_declaracion','parser.py',33),
  ('instruccion -> R_LET ID DOS_PUNTOS tipo IGUAL expresion PUNTO_COMA','instruccion',7,'p_instruccion_declaracion','parser.py',34),
  ('tipo -> R_I32','tipo',1,'p_tipo','parser.py',42),
  ('tipo -> R_F64','tipo',1,'p_tipo','parser.py',43),
  ('tipo -> R_STRING','tipo',1,'p_tipo','parser.py',44),
  ('tipo -> R_BOOL','tipo',1,'p_tipo','parser.py',45),
  ('expresion -> expresion MAS expresion','expresion',3,'p_expresion_binaria','parser.py',50),
  ('expresion -> expresion MENOS expresion','expresion',3,'p_expresion_binaria','parser.py',51),
  ('expresion -> expresion POR expresion','expresion',3,'p_expresion_binaria','parser.py',52),
  ('expresion -> expresion DIV expresion','expresion',3,'p_expresion_binaria','parser.py',53),
  ('expresion -> expresion MOD expresion','expresion',3,'p_expresion_binaria','parser.py',54),
  ('expresion -> ENTERO','expresion',1,'p_expresion_primitiva','parser.py',59),
  ('expresion -> DECIMAL','expresion',1,'p_expresion_primitiva','parser.py',60),
  ('expresion -> CADENA','expresion',1,'p_expresion_primitiva','parser.py',61),
  ('expresion -> R_TRUE','expresion',1,'p_expresion_primitiva','parser.py',62),
  ('expresion -> R_FALSE','expresion',1,'p_expresion_primitiva','parser.py',63),
]
